spring:
  datasource:
    # MySql
    url: jdbc:mysql://localhost:3306/locyk-boot?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.jdbc.Driver


  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /lqh # rabbitmq的虚拟host
    username: lqh # rabbitmq的用户名
    password: 1qaz2wsx # rabbitmq的密码
    publisher-confirm-type: correlated #如果对异步消息需要回调必须设置为true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

